#!/usr/bin/with-contenv bash

fix_ownership() {
    find "$@" \! \( -uid "$(id -u abc)" -gid "$(id -g abc)" \) -print0 | \
        xargs -0 --no-run-if-empty chown -h abc:abc
}

mkdir -p "${KAVITA_CONFIG_DIR}"

if [ ! -f "${KAVITA_CONFIG_FILE}" ]; then
    if [ -f "${KAVITA_GDS_TAR}" ]; then
        echo "*** Using $(basename "${KAVITA_GDS_TAR}"). Please be patient..."
        tar -C "$KAVITA_CONFIG_DIR" -zxf "${KAVITA_GDS_TAR}" --strip-components=1
        jq -r '.TokenKey = "super secret unguessable key"' "${KAVITA_CONFIG_FILE}" > /tmp/tmp.json && \
            mv /tmp/tmp.json "${KAVITA_CONFIG_FILE}"
        fix_ownership "$KAVITA_CONFIG_DIR"
        exit 0
    fi
    echo "*** Using default appsettings.json"
    cp "/defaults/appsettings.json" "${KAVITA_CONFIG_FILE}"
fi

fix_ownership "$KAVITA_CONFIG_DIR" /kavita/wwwroot

if [ "$ATIVAK" = "1" ]; then
    rm -rf \
        /overlay/work \
        /ativak/config && \
    mkdir -p \
        /overlay/{upper,work} \
        /ativak/config

    mount -t overlay overlay \
        -o lowerdir=/kavita/config,upperdir=/overlay/upper,workdir=/overlay/work \
        /ativak/config

    fix_ownership /ativak/config /ativak/wwwroot
fi
