#!/usr/bin/with-contenv bash

mkdir -p "${KAVITA_CONFIG_DIR}"

if [ ! -f "${KAVITA_CONFIG_FILE}" ]; then
    if [ -f "${KAVITA_GDS_TAR}" ]; then
        echo "*** Using $(basename ${KAVITA_GDS_TAR}). Please be patient..."
        tar -C "$KAVITA_CONFIG_DIR" -zxf "${KAVITA_GDS_TAR}" --strip-components=1
        jq -r '.TokenKey = "super secret unguessable key"' "${KAVITA_CONFIG_FILE}" > /tmp/tmp.json && \
            mv /tmp/tmp.json "${KAVITA_CONFIG_FILE}"
        chown -R abc:abc "$KAVITA_CONFIG_DIR"
        exit 0
    fi
    echo "*** Using default appsettings.json"
    cp "/defaults/appsettings.json" "${KAVITA_CONFIG_FILE}"
fi

find "$KAVITA_CONFIG_DIR" \! \( -uid $(id -u abc) -gid $(id -g abc) \) -print0 | \
    xargs -0 --no-run-if-empty chown -h abc:abc
